//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePhoneBook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbphonebookEntitiesContext : DbContext
    {
        public dbphonebookEntitiesContext()
            : base("name=dbphonebookEntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contactdetails_tb> contactdetails_tb { get; set; }
        public virtual DbSet<Country_tb> Country_tb { get; set; }
        public virtual DbSet<type_tb> type_tb { get; set; }
        public virtual DbSet<user_tb> user_tb { get; set; }
    }
}
